# Generated by Django 4.1.2 on 2022-10-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Categories',
        ),
    ]
