# Generated by Django 4.1.2 on 2022-10-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0002_rename_user_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='emailId',
            new_name='description',
        ),
    ]
