# Generated by Django 4.1.2 on 2022-10-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0003_rename_emailid_categories_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('emailId', models.CharField(max_length=500)),
                ('profilePicture', models.CharField(max_length=1000)),
            ],
        ),
    ]
