# Generated by Django 4.1.2 on 2022-10-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=100)),
                ('countryKey', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='categories',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='countries',
            field=models.TextField(null=True),
        ),
    ]
