# Generated by Django 4.1.2 on 2022-10-28 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0005_countries_users_categories_users_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='countryKey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='countryName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
