# Generated by Django 4.1.2 on 2022-10-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0006_alter_countries_countrykey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='countryKey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='countryName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
