# Generated by Django 4.1.2 on 2022-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0007_alter_countries_countrykey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('categoryId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('countryId', models.IntegerField()),
            ],
        ),
    ]
