# Generated by Django 4.1.3 on 2022-11-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0008_categorypreferences_countrypreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypreferences',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='adriaticsea.categories', verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='categorypreferences',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='adriaticsea.users', verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='countrypreferences',
            name='countryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='adriaticsea.countries', verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='countrypreferences',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='adriaticsea.users', verbose_name='Users'),
        ),
    ]
