# Generated by Django 4.1.3 on 2022-11-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0011_rename_categoryid_categorypreferences_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(max_length=300)),
                ('image', models.TextField(max_length=500)),
                ('posted', models.TextField(max_length=50)),
                ('time', models.DateTimeField()),
                ('detailednews', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
