# Generated by Django 4.1.3 on 2022-11-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0013_alter_news_image_alter_news_posted_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='time',
            new_name='posteddatetime',
        ),
        migrations.AddField(
            model_name='news',
            name='trend',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='adriaticsea.countries', verbose_name='Countries'),
        ),
    ]
