# Generated by Django 4.1.3 on 2022-11-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0014_rename_time_news_posteddatetime_news_trend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='posteddatetime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='trend',
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
