# Generated by Django 4.1.3 on 2022-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adriaticsea', '0018_alter_news_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posteddatetime',
            field=models.DateTimeField(null=True),
        ),
    ]
